### ISSUE TITLE
Consul is not retaining configuration between restarts

### ISSUE THREAD

**Issue by lenny-goodell** [edgexfoundry/docker-edgex-consul#1]
Consul Docker image by default is runs in `DEV` mode a doesn't save configuration to file. 
```
# By default you'll get an insecure single-node development server that stores
# everything in RAM, exposes a web UI and HTTP endpoints, and bootstraps itself.
# Don't use this configuration for production.
CMD ["agent", "-dev", "-client", "0.0.0.0"]
```

Add the following to the compose files for Consul to override the default so that it saves configuration between restarts.
` command: agent -ui -data-dir /consul/data -client 0.0.0.0 -server -bootstrap`

**Comment by tsconn23** [comment]
I transferred this issue here b/c in the Fuji release we'll have our own wrapped Consul image and we need to be sure and account for this.

**Comment by anonymouse64** [comment]
I believe all we need to do is just not run consul with `-dev`

**Comment by lenny-goodell** [comment]
Nope, when you remove -dev it expects other options that I have listed above. Specifically the data-dir.

**Comment by anonymouse64** [comment]
Sorry I just meant the option that is causing consul to not persist configuration is the -dev option, yes I'm aware we need to pass additional args when we remove -dev

**Comment by cloudxxx8** [comment]
Please refer to what we did before 
https://github.com/edgexfoundry/docker-core-consul/blob/master/Dockerfile

However, don’t clean up /consul/data* like this example because it will remove everything whenever restart consul

**Comment by bnevis-i** [comment]
We really ought to fix this (request file against fuji and geneva).  Note that if the first command is agent, `-data-dir` and `-config-dir` are specified automatically.  See [here](https://github.com/hashicorp/docker-consul/blob/master/0.X/docker-entrypoint.sh#L62)
