### ISSUE TITLE
Delete security-proxy-setup health check (not used)

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/docker-edgex-consul#27]
No edgex microservice blocks on security-proxy-setup to be completed.  Consequently, the health  check can be removed.   This also means that https://github.com/edgexfoundry/docker-edgex-consul/issues/17 need to be fixed as well.

Affected files:

- https://github.com/edgexfoundry/docker-edgex-consul/blob/master/scripts/security-proxy-setup-checker.sh (remove)
- https://github.com/edgexfoundry/docker-edgex-consul/blob/master/config/secure/02-security-proxy-setup.json (remove)
- https://github.com/edgexfoundry/docker-edgex-consul/blob/master/Dockerfile  (remove curl and jq depdencencies)

cc @mkbhanda

**Comment by mkbhanda** [comment]
Thank you @bnevis-i for doing the investigation and report out on this!
