### ISSUE TITLE
Disable consul update check

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/docker-edgex-consul#30]
Disable the consul update check.

```
2020-07-21T19:08:54.397Z [ERROR] agent: Failed to check for updates: error="Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=a930e0f0-772d-f78f-9c76-1c297d56d6ab&version=1.7.2: dial tcp 23.23.113.197:443: connect: connection refused"
```

According to this (https://redmine.ixsystems.com/issues/27383) there is a `--disable_update_check` switch.

**Comment by lenny-goodell** [comment]
@bnevis-i should  this be in Core Wg project? i.e. is it really a security issue or just tech debt?

**Comment by bnevis-i** [comment]
@lenny-intel 

The existence of a "phone-home" could be construed to be a security issue in certain use cases.  It also implies a requirement for internet connectivity.

The automatic logging of an out-of-date consul could be considered a useful feature as well, were there someone watching the logs, but I question its utility when the remediation is not to update the binary with a package manager but to instead replace the container.
