### ISSUE TITLE
Remove consul health checks

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/docker-edgex-consul#39]
This issue is part of implementation of secure bootstrapping ADR.

Replace consul health checks with simple TCP socket listeners and tools like wait-for-it.

Once done, the consul service health checks that are based on sentinel files can be removed.

**Comment by jim-wang-intel** [comment]
@lenny-intel or @jpwhitemn  if you have the written permission please add @beaufrusetta, @bnevis-i, @lenny-intel, @hutchic   as reviewers . I don't have that permission.  Thanks.

**Comment by bnevis-i** [comment]
Closed by https://github.com/edgexfoundry/developer-scripts/pull/372 (docker-edgex-consul deprecated)
