### ISSUE TITLE
Services fail to start when deployed on Kubernetes

### ISSUE THREAD

**Issue by sukruavcuoglu** [edgexfoundry/docker-edgex-consul#43]
Hello,

I am trying to install all Edgex Foundry micro services on Kubernetes. I created a Helm Chart for all services following the template from https://github.com/edgexfoundry/developer-scripts/blob/master/releases/hanoi/compose-files/docker-compose-hanoi-no-secty.yml

After Helm install command being applied all services except Consul, Redis, Kuiper and UI are failing to start.
I guess the main difference from running via docker-compose.yaml is services are able to find Core Consul service when they try to connect for the first time. If I start the services in a Docker environment they can not find the Core Consul service when they try to connect at first attempt.
 
The logs from Edgex Core Command service when running on Kubernetes:

`level=INFO ts=2020-12-07T10:44:12.816281446Z app=edgex-core-command source=config.go:193 msg="Loaded configuration from /res/configuration.toml"
level=INFO ts=2020-12-07T10:44:12.817027768Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Registry.Host' by environment variable: REGISTRY_HOST=edgex-core-consul"
level=INFO ts=2020-12-07T10:44:12.817103407Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Clients.Metadata.Host' by environment variable: CLIENTS_METADATA_HOST=edgex-core-metadata"
level=INFO ts=2020-12-07T10:44:12.817142795Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Service.Host' by environment variable: SERVICE_HOST=edgex-core-command"
level=INFO ts=2020-12-07T10:44:12.81733108Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Databases.Primary.Host' by environment variable: DATABASES_PRIMARY_HOST=edgex-redis"
level=INFO ts=2020-12-07T10:44:12.817573469Z app=edgex-core-command source=config.go:168 msg="Using Configuration provider (consul) from: http://edgex-core-consul:8500 with base path of edgex/core/1.0/edgex-core-command"
level=INFO ts=2020-12-07T10:44:12.833754274Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Databases.Primary.Host' by environment variable: DATABASES_PRIMARY_HOST=edgex-redis"
level=INFO ts=2020-12-07T10:44:12.834489558Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Registry.Host' by environment variable: REGISTRY_HOST=edgex-core-consul"
level=INFO ts=2020-12-07T10:44:12.834565738Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Clients.Metadata.Host' by environment variable: CLIENTS_METADATA_HOST=edgex-core-metadata"
level=INFO ts=2020-12-07T10:44:12.834679033Z app=edgex-core-command source=variables.go:394 msg="Variables override of 'Service.Host' by environment variable: SERVICE_HOST=edgex-core-command"
level=INFO ts=2020-12-07T10:44:12.835172578Z app=edgex-core-command source=config.go:304 msg="Configuration has been pulled from Configuration provider (4 envVars overrides applied)"
level=ERROR ts=2020-12-07T10:44:12.835209369Z app=edgex-core-command source=logger.go:74 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2020-12-07T10:44:12.835314116Z app=edgex-core-command source=registry.go:80 msg="Using Registry (consul) from http://edgex-core-consul:8500"
level=INFO ts=2020-12-07T10:44:12.877779584Z app=edgex-core-command source=database.go:147 msg="Database connected"
level=INFO ts=2020-12-07T10:44:12.878271505Z app=edgex-core-command source=telemetry.go:86 msg="Telemetry starting"
level=INFO ts=2020-12-07T10:44:12.878330912Z app=edgex-core-command source=httpserver.go:99 msg="Web server starting (edgex-core-command:48082)"
level=INFO ts=2020-12-07T10:44:12.878352662Z app=edgex-core-command source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2020-12-07T10:44:12.87836673Z app=edgex-core-command source=message.go:51 msg="Starting edgex-core-command 1.3.0 "
level=INFO ts=2020-12-07T10:44:12.878389886Z app=edgex-core-command source=message.go:55 msg="This is the Core Command Microservice"
level=INFO ts=2020-12-07T10:44:12.878416073Z app=edgex-core-command source=message.go:58 msg="Service started in: 63.345277ms"
level=INFO ts=2020-12-07T10:44:12.879632782Z app=edgex-core-command source=httpserver.go:107 msg="Web server stopped"
level=INFO ts=2020-12-07T10:45:41.874835546Z app=edgex-core-command source=httpserver.go:116 msg="Web server shutting down"
level=INFO ts=2020-12-07T10:45:41.874927848Z app=edgex-core-command source=httpserver.go:118 msg="Web server shut down"
level=INFO ts=2020-12-07T10:45:41.874959337Z app=edgex-core-command source=database.go:161 msg="Database disconnected"
level=INFO ts=2020-12-07T10:45:41.939392666Z app=edgex-core-command source=telemetry.go:98 msg="Telemetry stopped"
level=INFO ts=2020-12-07T10:45:41.939508883Z app=edgex-core-command source=bootstrap.go:127 msg="Un-Registering service from the Registry"`

Thanks,
Sukru

**Comment by bnevis-i** [comment]
It almost looks like Kubernetes is shutting the service down after 30 seconds.  Is a healthcheck configured that is causing the POD to be deemed failed?

**Comment by cloudxxx8** [comment]
Can you run the services without Consul?
Please try to override the CMD to only "--confdir=/res"
Consul is using by default when the container starts up
https://github.com/edgexfoundry/edgex-go/blob/7f9dd25f9d981fc062fb35c9729d56f5b41711bb/cmd/core-command/Dockerfile#L42

**Comment by lenny-goodell** [comment]
This is not an issue with Consul (as I indicated in the Slack discussion). As @bnevis-i commented and I pointed out in Slack, something is shutting down the services. Closing this issue. Discussion can continue in Slack.
